version: 0.2

phases :
  pre_build: 
    commands:
      - npm install
      - aws s3 rm s3://stefan-static-webiste --recursive 
  build: 
    commands:
      - npm run build

artifacts: 
  files:
  - '**/*'
  base-directory: out